name: Publish release

on:
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout latest code"
        uses: actions/checkout@v3

      - name: "Set up JDK 17"
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1

      - name: "Authenticate to Google using WIF"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.CDO_WORKLOAD_IDENTITY_PROVIDER_GCP }}
          service_account: cicd-service-account@cio-equip-inventory-np-e45a37.iam.gserviceaccount.com

      - name: "Publish package"
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: publish -Pversion=${{ github.event.release.tag_name }}
